spring:
  application:
    name: commit

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.fuuciatooaawrnkupjms
    password: bhavesh@Commit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

# Firebase configuration
firebase:
  credentials:
    path: firebase-service-account.json
    json: ${FIREBASE_CREDENTIALS_JSON:}
